In [1]:
import numpy as np
import pandas as pd
import random

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
order = pd.read_csv('/home/felix/Downloads/orders.csv')

/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (15,16,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
order.columns

Index(['akeed_order_id', 'customer_id', 'item_count', 'grand_total',
       'payment_mode', 'promo_code', 'vendor_discount_amount',
       'promo_code_discount_percentage', 'is_favorite', 'is_rated',
       'vendor_rating', 'driver_rating', 'deliverydistance', 'preparationtime',
       'delivery_time', 'order_accepted_time', 'driver_accepted_time',
       'ready_for_pickup_time', 'picked_up_time', 'delivered_time',
       'delivery_date', 'vendor_id', 'created_at', 'LOCATION_NUMBER',
       'LOCATION_TYPE', 'CID X LOC_NUM X VENDOR'],
      dtype='object')

In [4]:
order.shape

(135303, 26)

In [6]:
hy = order['CID X LOC_NUM X VENDOR']

In [7]:
hy = hy.drop_duplicates()

In [8]:
hy.shape

(80142,)

In [13]:
hy.value_counts()

P66OCMZ X 0 X 195    1
GDJ5Q3V X 1 X 79     1
V5EUZQT X 5 X 221    1
JV3V0UL X 1 X 577    1
LAQ989J X 2 X 197    1
9K33B7I X 1 X 86     1
6M6V4EF X 0 X 856    1
TFO0E97 X 0 X 43     1
KLT7AL8 X 0 X 161    1
K7XV6Q7 X 3 X 259    1
JFGJ8IG X 0 X 259    1
34517YM X 1 X 105    1
IIPHXPF X 0 X 66     1
511TAJS X 0 X 106    1
3KHFH3E X 0 X 582    1
CGUCESE X 0 X 85     1
QXRNSE0 X 0 X 203    1
ZWF27MA X 1 X 76     1
2SM6FIY X 0 X 78     1
HA8KJN6 X 2 X 578    1
GF5DIBK X 0 X 299    1
N046NOU X 0 X 55     1
R6ODDFJ X 1 X 537    1
SLN9OXT X 0 X 4      1
KNSNC27 X 0 X 243    1
20L1XC0 X 0 X 78     1
NL5B4SZ X 1 X 547    1
CJL8DZ0 X 1 X 401    1
EDOGG5S X 0 X 386    1
PZUIFGD X 0 X 195    1
                    ..
0H20BYF X 1 X 295    1
K22POF9 X 4 X 459    1
205VASC X 1 X 75     1
5PU6VVK X 2 X 84     1
5U33O4D X 2 X 92     1
YSKIVGD X 1 X 44     1
5NZHWV4 X 4 X 681    1
HF84FBJ X 0 X 294    1
JL4YV8J X 1 X 154    1
VGJFIGM X 0 X 33     1
WWPAZ1I X 0 X 203    1
Y60QXT5 X 1 X 189    1
IHOS56Z X 0 X 104    1
3LN4IGC X 1 X 547    1
DXPXP0A X 0 X 250    1
F9CNU4K X 0 X 113    1
88R02RZ X 0 X 176    1
A9EA627 X 0 X 578    1
VI1TE88 X 1 X 83     1
3NCC2TK X 1 X 43     1
XARUNI7 X 0 X 398    1
AJ18MXF X 0 X 386    1
7M5FUHJ X 1 X 154    1
AA65956 X 0 X 294    1
9Q2KD1Z X 1 X 149    1
SJSN19Q X 0 X 78     1
8DVDJTY X 2 X 76     1
GSO5B5S X 0 X 221    1
O4UBD2G X 1 X 84     1
F9FHQ82 X 0 X 104    1
Name: CID X LOC_NUM X VENDOR, Length: 80142, dtype: int64

In [6]:
order.dtypes

akeed_order_id                    float64
customer_id                        object
item_count                        float64
grand_total                       float64
payment_mode                        int64
promo_code                         object
vendor_discount_amount            float64
promo_code_discount_percentage    float64
is_favorite                        object
is_rated                           object
vendor_rating                     float64
driver_rating                     float64
deliverydistance                  float64
preparationtime                   float64
delivery_time                      object
order_accepted_time                object
driver_accepted_time               object
ready_for_pickup_time              object
picked_up_time                     object
delivered_time                     object
delivery_date                      object
vendor_id                           int64
created_at                         object
LOCATION_NUMBER                     int64
LOCATION_TYPE                      object
CID X LOC_NUM X VENDOR             object
dtype: object

In [9]:
order = order[['akeed_order_id', 'customer_id', 'item_count', 'grand_total', 'payment_mode', 'vendor_discount_amount', 'promo_code_discount_percentage', 'is_favorite', 'is_rated', 'vendor_rating', 'driver_rating', 'deliverydistance', 'preparationtime', 'vendor_id', 'LOCATION_NUMBER', 'LOCATION_TYPE', 'CID X LOC_NUM X VENDOR']]

In [10]:
order.head(5)

,akeed_order_id,customer_id,item_count,grand_total,payment_mode,vendor_discount_amount,promo_code_discount_percentage,is_favorite,is_rated,vendor_rating,driver_rating,deliverydistance,preparationtime,vendor_id,LOCATION_NUMBER,LOCATION_TYPE,CID X LOC_NUM X VENDOR
0,163238.0,92PEE24,1.0,7.6,2,0.0,NaN,NaN,No,NaN,0.0,0.0,NaN,105,0,NaN,92PEE24 X 0 X 105
1,163240.0,QS68UD8,1.0,8.7,1,0.0,NaN,NaN,No,NaN,0.0,0.0,NaN,294,0,Work,QS68UD8 X 0 X 294
2,163241.0,MB7VY5F,2.0,14.4,1,0.0,NaN,NaN,No,NaN,0.0,0.0,NaN,83,0,NaN,MB7VY5F X 0 X 83
3,163244.0,KDJ951Y,1.0,7.1,1,0.0,NaN,NaN,No,NaN,0.0,0.0,NaN,90,0,Home,KDJ951Y X 0 X 90
4,163245.0,BAL0RVT,4.0,27.2,1,0.0,NaN,NaN,No,NaN,0.0,0.0,NaN,83,0,Work,BAL0RVT X 0 X 83

In [11]:
order.shape

(135303, 17)

In [12]:
order.columns

Index(['akeed_order_id', 'customer_id', 'item_count', 'grand_total',
       'payment_mode', 'vendor_discount_amount',
       'promo_code_discount_percentage', 'is_favorite', 'is_rated',
       'vendor_rating', 'driver_rating', 'deliverydistance', 'preparationtime',
       'vendor_id', 'LOCATION_NUMBER', 'LOCATION_TYPE',
       'CID X LOC_NUM X VENDOR'],
      dtype='object')

In [13]:
duplicate_order = order[order.duplicated(['CID X LOC_NUM X VENDOR'])]
print(duplicate_order)

        akeed_order_id customer_id  item_count  grand_total  payment_mode  \
7             163248.0     I9DNSMJ         2.0         14.4             1
13            163257.0     DRR8CO9         2.0         11.4             1
57            163340.0     1WUPJGN         2.0         13.0             2
90            163407.0     FWNWSYH         1.0          7.6             1
136           163502.0     G5108U3         2.0         16.0             2
158           163541.0     OB15TZY         2.0          8.7             1
367           163956.0     II9FYLU         3.0          3.5             1
393           164026.0     CQMPL3W         2.0         10.1             1
406           164071.0     IFDT0BW         1.0          9.5             2
429           164122.0     QNZ8YW0         4.0         40.0             2
496           164262.0     N94XH2T         1.0         12.8             1
513           164301.0     D7GQVAR         2.0         24.3             1
562           164391.0     N8WINW9         1.0          4.6             1
573           164409.0     AZ0OGDU         4.0          8.4             1
578           164417.0     IZ17PI0         2.0         18.8             1
597           164456.0     N41VQEP         2.0          5.4             1
600           164460.0     CLXMEXI         3.0         19.8             2
611           164476.0     92PEE24         1.0          7.6             2
616           164488.0     179E40X         3.0         13.7             1
620           164502.0     X1DF55Z         1.0          6.5             1
648           164555.0     XW90EAP         2.0         16.2             2
655           164569.0     EL4KP47         2.0          7.3             1
666           164597.0     NY73W6G         1.0         10.6             2
680           164636.0     HX76ORD         5.0         34.0             2
688           164656.0     0ZU8WW6         2.0         11.1             1
689           164665.0     XP5OI1S         1.0          5.7             1
692           164671.0     XP5OI1S         1.0         10.9             1
706           164703.0     CRR5IEM         1.0         10.1             1
713           164716.0     HX76ORD         2.0          9.4             2
725           164745.0     VE6IAW5         4.0         20.8             2
...                ...         ...         ...          ...           ...
135242        415322.0     ORM0YE3         1.0          8.2             1
135243        415323.0     5Z1E2LV         4.0         13.3             1
135244        415326.0     6O1KTKP         3.0         35.4             2
135245        415329.0     9PRNQUG         2.0          7.3             1
135246        415332.0     ENS6KUT         1.0          7.4             1
135249        415335.0     C2Q96U9         2.0          7.1             1
135251        415340.0     HWFSAO0         3.0         11.4             2
135254        415350.0     987BLM4         1.0          8.6             1
135256        415352.0     XSZN083         3.0         13.0             2
135259        415364.0     R2PVLKU         1.0          9.9             4
135263        415374.0     3EABH9S         2.0          3.5             1
135264        415376.0     ZPHYRXY         4.0         16.3             2
135267        415388.0     ZZL4GJ1         3.0         42.4             4
135270        415401.0     3NKEFBB         2.0         16.4             2
135271        415402.0     7G0DQHO         2.0         10.7             1
135272        415407.0     DXHU96T         1.0          7.6             1
135275        415421.0     B0SIVPQ         2.0          9.8             1
135278        415424.0     L8TVFTK         1.0          0.8             1
135281        415447.0     CUS8M9I         2.0         12.2             2
135282        415448.0     XQ07TWN         1.0          9.0             4
135285        415457.0     CIXLEU0         1.0          7.0             1
135286        415460.0     AVD95T0         3.0         12.5             3
135288        415462.0     TV8AIWU         1.0          9.3             4
135289        415463.0     NE6ZHRW         3.0         43.6             2
135294        415481.0     FJ4MIOO         1.0          5.2             1
135295        415495.0     7MEVTSG         2.0          8.4             2
135297        415503.0     A1WOX6C         1.0          8.4             4
135298        415507.0     L6LFY6H         1.0         13.3             2
135299        415508.0     2GMMVGI         3.0          9.5             1
135301        415512.0     NEV9A5D         3.0          7.7             1

        vendor_discount_amount  promo_code_discount_percentage is_favorite  \
7                         0.00                             NaN         NaN
13                        0.00                             NaN         NaN
57                        0.00                             NaN         NaN
90                        0.00                             NaN         NaN
136                       0.00                             NaN         NaN
158                       0.00                             NaN         NaN
367                       0.00                             NaN         NaN
393                       0.00                             NaN         NaN
406                       0.00                             NaN         NaN
429                       0.00                             NaN         NaN
496                       0.00                             NaN         NaN
513                       0.00                             NaN         NaN
562                       0.00                             NaN         NaN
573                       0.00                             NaN         NaN
578                       0.00                             NaN         NaN
597                       0.00                             NaN         NaN
600                       0.00                             NaN         NaN
611                       0.00                             NaN         NaN
616                       0.00                             NaN         NaN
620                       0.00                             NaN         NaN
648                       0.00                             NaN         NaN
655                       0.00                             NaN         NaN
666                       0.00                             NaN         NaN
680                       0.00                             NaN         NaN
688                       0.00                             NaN         NaN
689                       0.00                             NaN         NaN
692                       0.00                             NaN         NaN
706                       0.00                             NaN         NaN
713                       0.00                             NaN         NaN
725                       0.00                             NaN         NaN
...                        ...                             ...         ...
135242                    0.00                             0.0          No
135243                    0.00                             0.0          No
135244                    0.00                             0.0          No
135245                    0.00                             0.0          No
135246                    0.36                             0.0          No
135249                    0.00                             0.0          No
135251                    0.00                             0.0          No
135254                    0.00                             0.0          No
135256                    0.00                             0.0          No
135259                    0.00                             0.0          No
135263                    0.00                             0.0          No
135264                    0.00                             0.0          No
135267                    0.00                             0.0          No
135270                    0.00                             0.0          No
135271                    0.00                             0.0          No
135272                    0.00                             0.0          No
135275                    0.00                             0.0          No
135278                    0.00                             0.0          No
135281                    0.00                             0.0          No
135282                    0.00                             0.0          No
135285                    0.00                             0.0          No
135286                    0.00                             0.0          No
135288                    0.00                             0.0          No
135289                    0.00                             0.0         Yes
135294                    0.00                             0.0          No
135295                    0.00                             0.0          No
135297                    0.00                             0.0          No
135298                    0.00                             0.0          No
135299                    0.00                             0.0          No
135301                    0.00                             0.0          No

       is_rated  vendor_rating  driver_rating  deliverydistance  \
7            No            NaN            0.0              0.00
13           No            NaN            0.0              0.00
57           No            NaN            0.0              0.00
90           No            NaN            0.0              0.00
136          No            NaN            0.0              0.00
158          No            NaN            0.0              0.00
367          No            NaN            0.0              0.00
393          No            NaN            0.0              0.00
406          No            NaN            0.0              0.00
429          No            NaN            0.0              0.00
496          No            NaN            0.0              0.00
513          No            NaN            0.0              0.00
562          No            NaN            0.0              0.00
573          No            NaN            0.0              0.00
578          No            NaN            0.0              0.00
597          No            NaN            0.0              0.00
600          No            NaN            0.0              0.00
611          No            NaN            0.0              0.00
616          No            NaN            0.0              0.00
620          No            NaN            0.0              0.00
648          No            NaN            0.0              0.00
655          No            NaN            0.0              0.00
666          No            NaN            0.0              0.00
680          No            NaN            0.0              0.00
688          No            NaN            0.0              0.00
689          No            NaN            0.0              0.00
692          No            NaN            0.0              0.00
706          No            NaN            0.0              0.00
713          No            NaN            0.0              0.00
725          No            NaN            0.0              0.00
...         ...            ...            ...               ...
135242       No            NaN            0.0              9.60
135243       No            NaN            0.0              4.74
135244       No            NaN            0.0             11.54
135245      Yes            5.0            4.0              6.49
135246       No            NaN            0.0              6.58
135249       No            NaN            0.0              2.22
135251      Yes            5.0            5.0              8.79
135254       No            NaN            0.0              7.95
135256       No            NaN            0.0              0.00
135259       No            NaN            0.0              7.75
135263       No            NaN            0.0              1.78
135264       No            NaN            0.0             10.42
135267       No            NaN            0.0              9.28
135270       No            NaN            0.0              3.04
135271       No            NaN            0.0             10.90
135272       No            NaN            0.0              9.89
135275       No            NaN            0.0              6.62
135278       No            NaN            0.0              6.59
135281       No            NaN            0.0              2.00
135282       No            NaN            0.0              5.12
135285      Yes            2.0            5.0              4.78
135286      Yes            5.0            5.0              9.50
135288       No            NaN            0.0              4.30
135289      Yes            5.0            5.0             11.53
135294       No            NaN            0.0              4.18
135295       No            NaN            0.0              3.71
135297       No            NaN            0.0              6.31
135298       No            NaN            0.0              1.75
135299      Yes            5.0            4.0             12.81
135301       No            NaN            0.0              2.29

        preparationtime  vendor_id  LOCATION_NUMBER LOCATION_TYPE  \
7                   NaN        105                0          Work
13                  NaN        154                0          Work
57                  NaN        221                0           NaN
90                  NaN          4                0          Work
136                 NaN        113                0          Work
158                 NaN         78                0          Home
367                 NaN         83                0          Home
393                 NaN        157                0          Home
406                 NaN        289                0          Home
429                 NaN        176                0          Home
496                 NaN        134                0           NaN
513                 NaN        192                0         Other
562                 NaN        157                0          Home
573                 NaN        199                0          Home
578                 NaN        196                0          Home
597                 NaN        161                0          Home
600                 NaN        105                0         Other
611                 NaN        105                0          Work
616                 NaN        271                0           NaN
620                 NaN        160                0          Home
648                 NaN         13                0           NaN
655                 NaN        231                0          Home
666                 NaN        113                0         Other
680                 NaN        159                0         Other
688                 NaN        105                0          Work
689                 NaN        160                0           NaN
692                 NaN         83                0           NaN
706                 NaN        271                0          Home
713                 NaN        300                0         Other
725                 NaN        300                0          Home
...                 ...        ...              ...           ...
135242             45.0        105                0         Other
135243             35.0        573                0           NaN
135244             45.0        188                0           NaN
135245             45.0         79                0         Other
135246             40.0        148                2          Home
135249             35.0         79                1          Home
135251             40.0        105                0          Work
135254             50.0        356                1           NaN
135256              NaN         44                0           NaN
135259             35.0        846                1           NaN
135263             40.0        907                0           NaN
135264             45.0        154                0          Home
135267             45.0         84                0           NaN
135270             35.0        846                1          Home
135271             50.0        299                0          Home
135272             45.0        105                3          Work
135275             45.0         79                1          Work
135278             50.0        907                0           NaN
135281             30.0        578                1         Other
135282             40.0        846                3          Home
135285             35.0        841                1          Home
135286             45.0        106                1          Home
135288             35.0        845                0           NaN
135289             50.0        188                0          Home
135294             35.0        547                1           NaN
135295             35.0        843                0          Work
135297             45.0        583                0           NaN
135298             40.0         67                0           NaN
135299             60.0         79                0          Work
135301             35.0        841                0           NaN

       CID X LOC_NUM X VENDOR
7           I9DNSMJ X 0 X 105
13          DRR8CO9 X 0 X 154
57          1WUPJGN X 0 X 221
90            FWNWSYH X 0 X 4
136         G5108U3 X 0 X 113
158          OB15TZY X 0 X 78
367          II9FYLU X 0 X 83
393         CQMPL3W X 0 X 157
406         IFDT0BW X 0 X 289
429         QNZ8YW0 X 0 X 176
496         N94XH2T X 0 X 134
513         D7GQVAR X 0 X 192
562         N8WINW9 X 0 X 157
573         AZ0OGDU X 0 X 199
578         IZ17PI0 X 0 X 196
597         N41VQEP X 0 X 161
600         CLXMEXI X 0 X 105
611         92PEE24 X 0 X 105
616         179E40X X 0 X 271
620         X1DF55Z X 0 X 160
648          XW90EAP X 0 X 13
655         EL4KP47 X 0 X 231
666         NY73W6G X 0 X 113
680         HX76ORD X 0 X 159
688         0ZU8WW6 X 0 X 105
689         XP5OI1S X 0 X 160
692          XP5OI1S X 0 X 83
706         CRR5IEM X 0 X 271
713         HX76ORD X 0 X 300
725         VE6IAW5 X 0 X 300
...                       ...
135242      ORM0YE3 X 0 X 105
135243      5Z1E2LV X 0 X 573
135244      6O1KTKP X 0 X 188
135245       9PRNQUG X 0 X 79
135246      ENS6KUT X 2 X 148
135249       C2Q96U9 X 1 X 79
135251      HWFSAO0 X 0 X 105
135254      987BLM4 X 1 X 356
135256       XSZN083 X 0 X 44
135259      R2PVLKU X 1 X 846
135263      3EABH9S X 0 X 907
135264      ZPHYRXY X 0 X 154
135267       ZZL4GJ1 X 0 X 84
135270      3NKEFBB X 1 X 846
135271      7G0DQHO X 0 X 299
135272      DXHU96T X 3 X 105
135275       B0SIVPQ X 1 X 79
135278      L8TVFTK X 0 X 907
135281      CUS8M9I X 1 X 578
135282      XQ07TWN X 3 X 846
135285      CIXLEU0 X 1 X 841
135286      AVD95T0 X 1 X 106
135288      TV8AIWU X 0 X 845
135289      NE6ZHRW X 0 X 188
135294      FJ4MIOO X 1 X 547
135295      7MEVTSG X 0 X 843
135297      A1WOX6C X 0 X 583
135298       L6LFY6H X 0 X 67
135299       2GMMVGI X 0 X 79
135301      NEV9A5D X 0 X 841

[55161 rows x 17 columns]

In [14]:
order = order.drop_duplicates(['CID X LOC_NUM X VENDOR'])

In [15]:
order.shape

(80142, 17)

In [16]:
duplicate_order = order[order.duplicated(['customer_id', 'item_count', 'grand_total', 'payment_mode', 'vendor_discount_amount', 'promo_code_discount_percentage', 'is_favorite', 'is_rated', 'vendor_rating', 'driver_rating', 'deliverydistance', 'preparationtime', 'vendor_id', 'LOCATION_NUMBER', 'LOCATION_TYPE', 'CID X LOC_NUM X VENDOR'])]
print(duplicate_order)

Empty DataFrame
Columns: [akeed_order_id, customer_id, item_count, grand_total, payment_mode, vendor_discount_amount, promo_code_discount_percentage, is_favorite, is_rated, vendor_rating, driver_rating, deliverydistance, preparationtime, vendor_id, LOCATION_NUMBER, LOCATION_TYPE, CID X LOC_NUM X VENDOR]
Index: []

In [10]:
order = order.drop_duplicates(['customer_id', 'item_count', 'grand_total', 'payment_mode', 'vendor_discount_amount', 'promo_code_discount_percentage', 'is_favorite', 'is_rated', 'vendor_rating', 'driver_rating', 'deliverydistance', 'preparationtime', 'vendor_id', 'LOCATION_NUMBER', 'LOCATION_TYPE', 'CID X LOC_NUM X VENDOR'])

In [17]:
order.shape

(80142, 17)

In [18]:
order.head()

,akeed_order_id,customer_id,item_count,grand_total,payment_mode,vendor_discount_amount,promo_code_discount_percentage,is_favorite,is_rated,vendor_rating,driver_rating,deliverydistance,preparationtime,vendor_id,LOCATION_NUMBER,LOCATION_TYPE,CID X LOC_NUM X VENDOR
0,163238.0,92PEE24,1.0,7.6,2,0.0,NaN,NaN,No,NaN,0.0,0.0,NaN,105,0,NaN,92PEE24 X 0 X 105
1,163240.0,QS68UD8,1.0,8.7,1,0.0,NaN,NaN,No,NaN,0.0,0.0,NaN,294,0,Work,QS68UD8 X 0 X 294
2,163241.0,MB7VY5F,2.0,14.4,1,0.0,NaN,NaN,No,NaN,0.0,0.0,NaN,83,0,NaN,MB7VY5F X 0 X 83
3,163244.0,KDJ951Y,1.0,7.1,1,0.0,NaN,NaN,No,NaN,0.0,0.0,NaN,90,0,Home,KDJ951Y X 0 X 90
4,163245.0,BAL0RVT,4.0,27.2,1,0.0,NaN,NaN,No,NaN,0.0,0.0,NaN,83,0,Work,BAL0RVT X 0 X 83

In [19]:
all_features = order


def percent_missing(df):
    data = pd.DataFrame(df)
    df__cols = list(pd.DataFrame(data))
    dict_x = {}
    for i in range(0, len(df_cols)):
        dict_x.update ({df_cols[i]: round(data[df_cols[i]].isnull().mean()*100, 2)})
    return  dict_x
df_cols = order.columns

missing = percent_missing(all_features)
df_miss = sorted(missing.items(), key=lambda x: x[1], reverse=True)

print('percent of missing data')
df_miss[0:17]

percent of missing data

[('vendor_rating', 63.59),
 ('promo_code_discount_percentage', 56.49),
 ('preparationtime', 44.93),
 ('LOCATION_TYPE', 38.4),
 ('is_favorite', 26.41),
 ('item_count', 5.52),
 ('akeed_order_id', 0.02),
 ('customer_id', 0.0),
 ('grand_total', 0.0),
 ('payment_mode', 0.0),
 ('vendor_discount_amount', 0.0),
 ('is_rated', 0.0),
 ('driver_rating', 0.0),
 ('deliverydistance', 0.0),
 ('vendor_id', 0.0),
 ('LOCATION_NUMBER', 0.0),
 ('CID X LOC_NUM X VENDOR', 0.0)]

In [ ]:
sns.set_style('white')
f, ax = plt.subplots(figsize=(8, 7))
sns.set_color_codes(palette='deep')
missing = round(order.isnull().mean()*100,2)
missing = missing[missing > 0]
missing.sort_values(inplace=True)
missing.plot.bar(color='b')

ax.xaxis.grid(False)
ax.set(ylabel='Percent of missing values')
ax.set(xlabel='Features')
ax.set(title='Percent of missing data')
sns.despine(trim=True, left=True)

In [20]:
order.dtypes

akeed_order_id                    float64
customer_id                        object
item_count                        float64
grand_total                       float64
payment_mode                        int64
vendor_discount_amount            float64
promo_code_discount_percentage    float64
is_favorite                        object
is_rated                           object
vendor_rating                     float64
driver_rating                     float64
deliverydistance                  float64
preparationtime                   float64
vendor_id                           int64
LOCATION_NUMBER                     int64
LOCATION_TYPE                      object
CID X LOC_NUM X VENDOR             object
dtype: object

In [21]:
order['LOCATION_TYPE'].value_counts()

Home     29625
Work     10262
Other     9484
Name: LOCATION_TYPE, dtype: int64

In [22]:
order['akeed_order_id'].value_counts()

253208.0    2
251526.0    2
230638.0    2
230682.0    2
230686.0    2
251897.0    2
230684.0    2
252730.0    2
340215.0    1
404014.0    1
141645.0    1
383021.0    1
174414.0    1
239963.0    1
283295.0    1
283294.0    1
141644.0    1
251339.0    1
220409.0    1
263374.0    1
239307.0    1
138254.0    1
216676.0    1
207179.0    1
311598.0    1
174402.0    1
275232.0    1
234691.0    1
283271.0    1
340209.0    1
           ..
388212.0    1
185450.0    1
305333.0    1
407186.0    1
305365.0    1
247469.0    1
218219.0    1
305367.0    1
313564.0    1
185452.0    1
152677.0    1
185444.0    1
263316.0    1
152675.0    1
414675.0    1
305334.0    1
125486.0    1
223442.0    1
370873.0    1
306670.0    1
250974.0    1
370877.0    1
250975.0    1
305345.0    1
229213.0    1
185441.0    1
400828.0    1
152674.0    1
256656.0    1
163840.0    1
Name: akeed_order_id, Length: 80117, dtype: int64

In [23]:
def handl_miss(ord):
    ord['akeed_order_id'] = order['akeed_order_id'].interpolate()
    ord['item_count'] = order['item_count'].fillna(1)
    ord['is_favorite'] = order['is_favorite'].fillna('No')
    ord['LOCATION_TYPE'] = order['LOCATION_TYPE'].interpolate(method='pad')
    ord['preparationtime'] = order['preparationtime'].fillna(40)
    ord['promo_code_discount_percentage'] = order['promo_code_discount_percentage'].fillna(0)
    ord['vendor_rating'] = order['vendor_rating'].fillna(order['vendor_rating'].median())
    return ord

In [24]:
order = handl_miss(order)

In [25]:
missing = percent_missing(order)
df_miss = sorted(missing.items(), key=lambda x: x[1], reverse=True)
print('percent of missing data')
df_miss[0:17]

percent of missing data

[('akeed_order_id', 0.0),
 ('customer_id', 0.0),
 ('item_count', 0.0),
 ('grand_total', 0.0),
 ('payment_mode', 0.0),
 ('vendor_discount_amount', 0.0),
 ('promo_code_discount_percentage', 0.0),
 ('is_favorite', 0.0),
 ('is_rated', 0.0),
 ('vendor_rating', 0.0),
 ('driver_rating', 0.0),
 ('deliverydistance', 0.0),
 ('preparationtime', 0.0),
 ('vendor_id', 0.0),
 ('LOCATION_NUMBER', 0.0),
 ('LOCATION_TYPE', 0.0),
 ('CID X LOC_NUM X VENDOR', 0.0)]

In [26]:
order['akeed_order_id'].value_counts()

230686.0    2
253208.0    2
251526.0    2
230682.0    2
230638.0    2
251897.0    2
230684.0    2
252730.0    2
340215.0    1
404014.0    1
141645.0    1
383021.0    1
174414.0    1
239963.0    1
138254.0    1
283294.0    1
141644.0    1
283295.0    1
251339.0    1
220409.0    1
239307.0    1
414359.0    1
216676.0    1
207179.0    1
311598.0    1
174402.0    1
275232.0    1
234691.0    1
283271.0    1
340209.0    1
           ..
185448.0    1
218217.0    1
277906.0    1
185450.0    1
407186.0    1
305365.0    1
247469.0    1
218219.0    1
305367.0    1
313564.0    1
185444.0    1
263316.0    1
152675.0    1
256656.0    1
305333.0    1
414675.0    1
305334.0    1
125486.0    1
223442.0    1
370873.0    1
306670.0    1
250974.0    1
370877.0    1
250975.0    1
305345.0    1
229213.0    1
185441.0    1
400828.0    1
152674.0    1
163840.0    1
Name: akeed_order_id, Length: 80134, dtype: int64

In [27]:
order.dtypes

akeed_order_id                    float64
customer_id                        object
item_count                        float64
grand_total                       float64
payment_mode                        int64
vendor_discount_amount            float64
promo_code_discount_percentage    float64
is_favorite                        object
is_rated                           object
vendor_rating                     float64
driver_rating                     float64
deliverydistance                  float64
preparationtime                   float64
vendor_id                           int64
LOCATION_NUMBER                     int64
LOCATION_TYPE                      object
CID X LOC_NUM X VENDOR             object
dtype: object

In [28]:
order['akeed_order_id'] = order['akeed_order_id'].astype(int)
order['item_count'] = order['item_count'].astype(int)
order['payment_mode'] = order['payment_mode'].astype('category')
order['is_favorite'] = order['is_favorite'].astype('category')
order['is_rated'] = order['is_rated'].astype('category')
order['vendor_id'] = order['vendor_id'].astype('category')
order['LOCATION_NUMBER'] = order['LOCATION_NUMBER'].astype('category')
order['LOCATION_TYPE'] = order['LOCATION_TYPE'].astype('category')

In [29]:
order.dtypes

akeed_order_id                       int64
customer_id                         object
item_count                           int64
grand_total                        float64
payment_mode                      category
vendor_discount_amount             float64
promo_code_discount_percentage     float64
is_favorite                       category
is_rated                          category
vendor_rating                      float64
driver_rating                      float64
deliverydistance                   float64
preparationtime                    float64
vendor_id                         category
LOCATION_NUMBER                   category
LOCATION_TYPE                     category
CID X LOC_NUM X VENDOR              object
dtype: object

In [30]:
order.head()

,akeed_order_id,customer_id,item_count,grand_total,payment_mode,vendor_discount_amount,promo_code_discount_percentage,is_favorite,is_rated,vendor_rating,driver_rating,deliverydistance,preparationtime,vendor_id,LOCATION_NUMBER,LOCATION_TYPE,CID X LOC_NUM X VENDOR
0,163238,92PEE24,1,7.6,2,0.0,0.0,No,No,0.0,0.0,0.0,40.0,105,0,NaN,92PEE24 X 0 X 105
1,163240,QS68UD8,1,8.7,1,0.0,0.0,No,No,0.0,0.0,0.0,40.0,294,0,Work,QS68UD8 X 0 X 294
2,163241,MB7VY5F,2,14.4,1,0.0,0.0,No,No,0.0,0.0,0.0,40.0,83,0,Work,MB7VY5F X 0 X 83
3,163244,KDJ951Y,1,7.1,1,0.0,0.0,No,No,0.0,0.0,0.0,40.0,90,0,Home,KDJ951Y X 0 X 90
4,163245,BAL0RVT,4,27.2,1,0.0,0.0,No,No,0.0,0.0,0.0,40.0,83,0,Work,BAL0RVT X 0 X 83

In [31]:
order['CID X LOC_NUM X VENDOR'].value_counts()

LMIB9T1 X 2 X 575    1
GYDGFFJ X 0 X 85     1
B9WMW6N X 0 X 149    1
HDW7QPY X 0 X 386    1
WJN75GZ X 0 X 289    1
BNZ75P7 X 0 X 193    1
1LZAGNZ X 1 X 577    1
ZZJSJYC X 0 X 271    1
T5V0NYA X 1 X 537    1
7T2JR6M X 0 X 104    1
MAFLLWT X 1 X 159    1
EB6G5XE X 1 X 575    1
8PBQKLH X 0 X 300    1
C9JPX95 X 1 X 676    1
30FA6JH X 0 X 386    1
FRBAFP4 X 4 X 92     1
JKDC9XL X 1 X 86     1
JRVM3EO X 1 X 459    1
JU554BP X 2 X 86     1
8GR8D4Q X 1 X 295    1
0YMPZLT X 0 X 90     1
3IHFZG9 X 0 X 386    1
IAVE0AF X 0 X 85     1
FINZB1J X 1 X 583    1
NWNWQWW X 1 X 105    1
FY7T803 X 1 X 104    1
TMGFF99 X 5 X 81     1
WYJVRX8 X 0 X 78     1
141REOU X 1 X 104    1
MAOM4IQ X 0 X 115    1
                    ..
SDQR5EC X 2 X 195    1
1VGJ69S X 0 X 134    1
NX4LU4L X 0 X 113    1
YU90KWF X 1 X 243    1
HNYOE0U X 0 X 66     1
8U1O485 X 0 X 105    1
JICF27K X 0 X 92     1
ZZBPHU4 X 0 X 855    1
FIC3GGQ X 4 X 855    1
WWJLJYZ X 0 X 113    1
U3K0KU1 X 0 X 83     1
26IVNSC X 1 X 154    1
JNQ41B5 X 1 X 681    1
WGXXHSE X 1 X 681    1
7P1DU6L X 1 X 419    1
4MPOELR X 1 X 856    1
VGXJ0NP X 2 X 176    1
MKRM10I X 0 X 203    1
QDPDAT5 X 1 X 154    1
OM1VPKR X 1 X 237    1
EW5L6U0 X 0 X 84     1
SO2UBJ0 X 0 X 79     1
J1YY2V0 X 0 X 83     1
BDHW02I X 2 X 78     1
WM6KURU X 0 X 83     1
K4TH4B4 X 1 X 310    1
VU7JW7F X 1 X 84     1
21DQ1CX X 0 X 195    1
MZPBM89 X 2 X 79     1
LG6TPO0 X 0 X 83     1
Name: CID X LOC_NUM X VENDOR, Length: 80142, dtype: int64