In [1]:
import pandas as pd
import numpy as np


import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from ast import literal_eval
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
vendor = pd.read_csv('/home/felix/Downloads/vendors.csv')

In [ ]:
vendor.dtypes

In [3]:
vendor.columns

Index(['id', 'authentication_id', 'latitude', 'longitude',
       'vendor_category_en', 'vendor_category_id', 'delivery_charge',
       'serving_distance', 'is_open', 'OpeningTime', 'OpeningTime2',
       'prepration_time', 'commission', 'is_akeed_delivering',
       'discount_percentage', 'status', 'verified', 'rank', 'language',
       'vendor_rating', 'sunday_from_time1', 'sunday_to_time1',
       'sunday_from_time2', 'sunday_to_time2', 'monday_from_time1',
       'monday_to_time1', 'monday_from_time2', 'monday_to_time2',
       'tuesday_from_time1', 'tuesday_to_time1', 'tuesday_from_time2',
       'tuesday_to_time2', 'wednesday_from_time1', 'wednesday_to_time1',
       'wednesday_from_time2', 'wednesday_to_time2', 'thursday_from_time1',
       'thursday_to_time1', 'thursday_from_time2', 'thursday_to_time2',
       'friday_from_time1', 'friday_to_time1', 'friday_from_time2',
       'friday_to_time2', 'saturday_from_time1', 'saturday_to_time1',
       'saturday_from_time2', 'saturday_to_time2', 'primary_tags',
       'open_close_flags', 'vendor_tag', 'vendor_tag_name', 'one_click_vendor',
       'country_id', 'city_id', 'created_at', 'updated_at', 'device_type',
       'display_orders'],
      dtype='object')

In [4]:
vendor = vendor[['OpeningTime', 'OpeningTime2', 'sunday_from_time1', 'sunday_to_time1', 'primary_tags', 'vendor_tag', 'vendor_tag_name']]

In [4]:
vendor.head()

,OpeningTime,OpeningTime2,sunday_from_time1,sunday_to_time1,primary_tags,vendor_tag,vendor_tag_name
0,11:00AM-11:30PM,-,00:00:00,00:30:00,"{""primary_tags"":""4""}","2,4,5,8,91,22,12,24,16,23","Arabic,Breakfast,Burgers,Desserts,Free Deliver..."
1,08:30AM-10:30PM,-,00:00:00,01:30:00,"{""primary_tags"":""7""}","4,41,51,34,27,15,24,16,28","Breakfast,Cakes,Crepes,Italian,Pasta,Pizzas,Sa..."
2,08:00AM-10:45PM,-,08:00:00,22:45:00,"{""primary_tags"":""71""}","4,8,91,10","Breakfast,Desserts,Free Delivery,Indian"
3,10:59AM-10:30PM,-,09:00:00,23:30:00,"{""primary_tags"":""46""}","5,8,30,24","Burgers,Desserts,Fries,Salads"
4,11:00AM-11:45PM,-,00:01:00,00:30:00,"{""primary_tags"":""32""}",5,Burgers

In [5]:
vendor.dtypes

OpeningTime          object
OpeningTime2         object
sunday_from_time1    object
sunday_to_time1      object
primary_tags         object
vendor_tag           object
vendor_tag_name      object
dtype: object

In [6]:
vendor['primary_tags'] = vendor['primary_tags'].fillna('[]')
vendor['primary_tags'] = vendor['primary_tags'].apply(literal_eval)

In [7]:
vendor['vendor_tag_name'] = vendor['vendor_tag_name'].fillna('[]')

def to_list(string):
    ls = list(string.split(','))
    return ls
vendor['vendor_tag_name'] = vendor['vendor_tag_name'].apply(to_list)

In [8]:
vendor['vendor_tag'] = vendor['vendor_tag'].fillna('[]')

vendor['vendor_tag'] = vendor['vendor_tag'].apply(to_list)

In [20]:
vendor.head()

,OpeningTime2,OpeningTime2,sunday_from_time1,sunday_to_time1,primary_tags,vendor_tag,vendor_tag_name
0,-,-,00:00:00,00:30:00,{'primary_tags': '4'},"[2, 4, 5, 8, 91, 22, 12, 24, 16, 23]","[Arabic, Breakfast, Burgers, Desserts, Free De..."
1,-,-,00:00:00,01:30:00,{'primary_tags': '7'},"[4, 41, 51, 34, 27, 15, 24, 16, 28]","[Breakfast, Cakes, Crepes, Italian, Pasta, Piz..."
2,-,-,08:00:00,22:45:00,{'primary_tags': '71'},"[4, 8, 91, 10]","[Breakfast, Desserts, Free Delivery, Indian]"
3,-,-,09:00:00,23:30:00,{'primary_tags': '46'},"[5, 8, 30, 24]","[Burgers, Desserts, Fries, Salads]"
4,-,-,00:01:00,00:30:00,{'primary_tags': '32'},[5],[Burgers]

In [9]:
vendor['primary_tags'] = vendor['primary_tags'].str.get('primary_tags')

In [10]:
vendor.head()

,OpeningTime,OpeningTime2,sunday_from_time1,sunday_to_time1,primary_tags,vendor_tag,vendor_tag_name
0,11:00AM-11:30PM,-,00:00:00,00:30:00,4,"[2, 4, 5, 8, 91, 22, 12, 24, 16, 23]","[Arabic, Breakfast, Burgers, Desserts, Free De..."
1,08:30AM-10:30PM,-,00:00:00,01:30:00,7,"[4, 41, 51, 34, 27, 15, 24, 16, 28]","[Breakfast, Cakes, Crepes, Italian, Pasta, Piz..."
2,08:00AM-10:45PM,-,08:00:00,22:45:00,71,"[4, 8, 91, 10]","[Breakfast, Desserts, Free Delivery, Indian]"
3,10:59AM-10:30PM,-,09:00:00,23:30:00,46,"[5, 8, 30, 24]","[Burgers, Desserts, Fries, Salads]"
4,11:00AM-11:45PM,-,00:01:00,00:30:00,32,[5],[Burgers]

In [32]:
s = vendor['primary_tags']
s = s.get('primary_tags')
print(s)

None

In [30]:
s.head()

AttributeError: 'NoneType' object has no attribute 'head'

In [9]:
vendor['vendor_tag'].value_counts()

1,4,5,6,8,91,30,43,48,24        7
38,16,23                        3
31,8,10,44,33                   3
1,5,91,29,27                    3
60,38,61,16,36                  3
4,8,22,32,24,16,28              3
1,5,30,16                       2
5,8,91,27,16                    2
1,5,48,27,16,36,28,35           2
38,32,52,16,23                  2
41,57                           1
38,9,36                         1
4,5,8,10,24                     1
4,8,91,10                       1
1,5,16                          1
3,8,9,11,24,54                  1
31,8,10,33,67,21                1
2,5,16,23,22,15,8               1
60,62,86,25                     1
3,58,22,11,33,28                1
4,8,24,2                        1
38,12,16,23                     1
4,5,22,89,16,23                 1
4,8,12,50,15,24,16              1
1,5,8,57,30,27,24,16            1
1,5,8,91,30,29,48               1
91,38,90,24,16                  1
5,8,91,22,42                    1
3,8,33,24,28,19                 1
2,4,5,8,91,22,12,24,16,23       1
                               ..
8,42                            1
1,4,5,8,34,24,16,28,35          1
41,51,8,57,38,43,32,62,25       1
1,5,47,24,16                    1
2,4,8,53,13,24,16               1
91,42,24                        1
1,5,48,16                       1
2,31,7,22,10,33,24,28,19        1
8,91,38,9,43,32,52              1
46,52,16                        1
8,91,9,56                       1
1,5,8,52,27                     1
41,51,8,57,38,43,32,52,62,25    1
3,38,48                         1
34,27,15,24,16                  1
5                               1
2,22,10,27,24,17,28,56          1
2                               1
64,36                           1
5,8,63,15                       1
4,91,38,30,79,52,45             1
5,30,22,47,52,16,56             1
16,23,38,52,32                  1
1,4,45,24,16                    1
4,41,51,34,27,15,24,16,28       1
1,5,8,91,30,48,24               1
15,34,4,28,27,24,8              1
26,8,24                         1
80                              1
60,73                           1
Name: vendor_tag, Length: 77, dtype: int64

In [4]:
vendor.columns

Index(['id', 'latitude', 'longitude', 'vendor_category_en', 'delivery_charge',
       'serving_distance', 'is_open', 'prepration_time', 'discount_percentage',
       'status', 'verified', 'rank', 'vendor_rating', 'primary_tags'],
      dtype='object')

In [ ]:
#change column name id to VENDOR_ID
vendor = vendor.rename({'id':'VENDOR'}, axis=1)
#change index to VENDOR_ID
vendor = vendor.reindex(columns=['VENDOR'])

In [3]:
cat_cols = vendor.select_dtypes(include='object').columns
for col in cat_cols:
    print('number of classes in {}'.format((col)))
    print(vendor[col].nunique())
    print('-----------------------------------')

number of classes in vendor_category_en
2
-----------------------------------
number of classes in OpeningTime
68
-----------------------------------
number of classes in OpeningTime2
11
-----------------------------------
number of classes in is_akeed_delivering
1
-----------------------------------
number of classes in language
1
-----------------------------------
number of classes in sunday_from_time1
19
-----------------------------------
number of classes in sunday_to_time1
27
-----------------------------------
number of classes in sunday_from_time2
16
-----------------------------------
number of classes in sunday_to_time2
7
-----------------------------------
number of classes in monday_from_time1
20
-----------------------------------
number of classes in monday_to_time1
28
-----------------------------------
number of classes in monday_from_time2
16
-----------------------------------
number of classes in monday_to_time2
7
-----------------------------------
number of classes in tuesday_from_time1
20
-----------------------------------
number of classes in tuesday_to_time1
26
-----------------------------------
number of classes in tuesday_from_time2
15
-----------------------------------
number of classes in tuesday_to_time2
6
-----------------------------------
number of classes in wednesday_from_time1
19
-----------------------------------
number of classes in wednesday_to_time1
28
-----------------------------------
number of classes in wednesday_from_time2
15
-----------------------------------
number of classes in wednesday_to_time2
8
-----------------------------------
number of classes in thursday_from_time1
20
-----------------------------------
number of classes in thursday_to_time1
27
-----------------------------------
number of classes in thursday_from_time2
16
-----------------------------------
number of classes in thursday_to_time2
7
-----------------------------------
number of classes in friday_from_time1
23
-----------------------------------
number of classes in friday_to_time1
22
-----------------------------------
number of classes in friday_from_time2
16
-----------------------------------
number of classes in friday_to_time2
7
-----------------------------------
number of classes in saturday_from_time1
24
-----------------------------------
number of classes in saturday_to_time1
24
-----------------------------------
number of classes in saturday_from_time2
17
-----------------------------------
number of classes in saturday_to_time2
7
-----------------------------------
number of classes in primary_tags
42
-----------------------------------
number of classes in vendor_tag
77
-----------------------------------
number of classes in vendor_tag_name
77
-----------------------------------
number of classes in one_click_vendor
1
-----------------------------------
number of classes in created_at
100
-----------------------------------
number of classes in updated_at
98
-----------------------------------

In [ ]:
vendor.dtypes

In [ ]:
vendor['primary_tags'] = vendor['primary_tags'].astype(str)

In [ ]:
vendor.head()

In [ ]:
vendor['primary_tags'] = vendor['primary_tags'].str.get('home_tags')
#vendor['vendor_tag_name'] = vendor['vendor_tag_name'].str.split(',')
#vendor = vendor.explode('vendor_tag_name').reset_index(drop=True)

In [ ]:
vendor.head()

In [ ]:
h.values()

In [ ]:
{0: '{"primary_tags":"4"}',
 1: '{"primary_tags":"7"}',
 2: '{"primary_tags":"71"}',
 3: '{"primary_tags":"46"}',
 4: '{"primary_tags":"32"}',
 5: '{"primary_tags":"51"}',
 6: '{"primary_tags":"8"}',
 7: '{"primary_tags":"8"}',
 8: '{"primary_tags":"21"}',
 9: '{"primary_tags":"271"}',
 10: '{"primary_tags":"129"}',
 11: nan,
 12: '{"primary_tags":"24"}',
 13: nan,
 14: '{"primary_tags":"323"}',
 15: nan,
 16: '{"primary_tags":"134"}',
 17: nan,
 18: '{"primary_tags":"90"}',
 19: nan,
 20: '{"primary_tags":"336"}',
 21: '{"primary_tags":"90"}',
 22: '{"primary_tags":"31"}',
 23: '{"primary_tags":"134"}',
 24: '{"primary_tags":"134"}',
 25: '{"primary_tags":"32"}',
 26: '{"primary_tags":"46"}',
 27: '{"primary_tags":"462"}',
 28: '{"primary_tags":"138"}',
 29: '{"primary_tags":"534"}',
 30: nan,
 31: '{"primary_tags":"134"}',
 32: nan,
 33: nan,
 34: '{"primary_tags":"297"}',
 35: '{"primary_tags":"35"}',
 36: '{"primary_tags":"24"}',
 37: nan,
 38: '{"primary_tags":"21"}',
 39: nan,
 40: '{"primary_tags":"695"}',
 41: '{"primary_tags":"701"}',
 42: '{"primary_tags":"701"}',
 43: '{"primary_tags":"701"}',
 44: nan,
 45: nan,
 46: nan,
 47: '{"primary_tags":"270"}',
 48: nan,
 49: nan,
 50: '{"primary_tags":"52"}',
 51: nan,
 52: '{"primary_tags":"815"}',
 53: '{"primary_tags":"849"}',
 54: '{"primary_tags":"346"}',
 55: nan,
 56: nan,
 57: nan,
 58: '{"primary_tags":"47"}',
 59: '{"primary_tags":"134"}',
 60: '{"primary_tags":"28"}',
 61: '{"primary_tags":"134"}',
 62: '{"primary_tags":"180"}',
 63: '{"primary_tags":"204"}',
 64: '{"primary_tags":"8"}',
 65: '{"primary_tags":"260"}',
 66: '{"primary_tags":"1088"}',
 67: '{"primary_tags":"478"}',
 68: '{"primary_tags":"1065"}',
 69: '{"primary_tags":"1088"}',
 70: '{"primary_tags":"1088"}',
 71: '{"primary_tags":"32"}',
 72: '{"primary_tags":"1147"}',
 73: '{"primary_tags":"46"}',
 74: '{"primary_tags":"1348"}',
 75: nan,
 76: nan,
 77: '{"primary_tags":"1256"}',
 78: nan,
 79: '{"primary_tags":"8"}',
 80: '{"primary_tags":"8"}',
 81: '{"primary_tags":"28"}',
 82: '{"primary_tags":"134"}',
 83: nan,
 84: '{"primary_tags":"15"}',
 85: '{"primary_tags":"134"}',
 86: '{"primary_tags":"134"}',
 87: '{"primary_tags":"134"}',
 88: '{"primary_tags":"2072"}',
 89: '{"primary_tags":"2072"}',
 90: '{"primary_tags":"2072"}',
 91: '{"primary_tags":"2396"}',
 92: '{"primary_tags":"2396"}',
 93: '{"primary_tags":"2396"}',
 94: '{"primary_tags":"2396"}',
 95: '{"primary_tags":"2396"}',
 96: '{"primary_tags":"2396"}',
 97: '{"primary_tags":"2396"}',
 98: '{"primary_tags":"2396"}',
 99: '{"primary_tags":"24"}'}

In [ ]:
vendor.shape

In [ ]:
#convert 'vendor_category_en' and 'is_open' to astype.category
cat_cols = ['vendor_category_en', 'is_open']
encoder = ce.OrdinalEncoder((cols=cat_cols))
vendor = encoder.fit_transform(vendor)

#convert 'status' to category
map_status = {'0' : 0, '1.0' : 1}
vendor['status'] = vendor['status'].map(map_status)
#convert 'verified' to category
map_verified = {'0' : 0, '1' : 1}
vendor['verified'] = vendor['verified'].map(map_verified)
#convert rank to category
map_rank = {'1' : 1, '11' : 2}
vendor['rank'] = vendor['rank'].map(map_rank)
#extract int form primary tag
vendor['primary_tags'] = vendor['primary_tags'].fillna('[]')
vendor['primary_tags'] = vendor['primary_tags'].apply(literal_eval)
vendor['primary_tags'] = vendor['primary_tags'].apply(lambda x: [i['primary_tags'] for i in x] if isinstance(x, list) else [])


#convert vendor_tag_name to vector

s = vendor.apply(lambda x: pd.Series(x['vendor_tag_name']), axis=1).stack().reset_index(level=1, drop=True)


#plot latitude and longitude([hue='delivery_charge', 'vendor_category', 'is_open', 'status', 'verified', 'rank'] 
#                            [size='serving_distance', 'preparation_time', 'discount', 'vendor_rating'])

In [ ]:
from pandas.api.types import CategoricalDtype

In [ ]:
f = {'{"primary_tags":"1"}', '{"primary_tags":"2"}', '{"primary_tags":"3"}', '{"primary_tags":"4"}'}

In [ ]:
vendor['primary_tags'] = vendor['primary_tags'].str[7:]

In [ ]:
def pri_tag():
    for primary_tags in vendor['primary_tags']:
        if len(primary_tags) = 21:
            return primary_tags.str[17:19]
        else:
            return primary_tags.str[17:18]

In [5]:
vendor.head()

,id,latitude,longitude,vendor_category_en,delivery_charge,serving_distance,is_open,prepration_time,discount_percentage,status,verified,rank,vendor_rating,primary_tags,vendor_tag_name
0,4,-0.588596,0.754434,Restaurants,0.0,6.0,1.0,15,0.0,1.0,1,11,4.4,"{""primary_tags"":""4""}","Arabic,Breakfast,Burgers,Desserts,Free Deliver..."
1,13,-0.471654,0.744470,Restaurants,0.7,5.0,1.0,14,0.0,1.0,1,11,4.7,"{""primary_tags"":""7""}","Breakfast,Cakes,Crepes,Italian,Pasta,Pizzas,Sa..."
2,20,-0.407527,0.643681,Restaurants,0.0,8.0,1.0,19,0.0,1.0,1,1,4.5,"{""primary_tags"":""71""}","Breakfast,Desserts,Free Delivery,Indian"
3,23,-0.585385,0.753811,Restaurants,0.0,5.0,1.0,16,0.0,1.0,1,11,4.5,"{""primary_tags"":""46""}","Burgers,Desserts,Fries,Salads"
4,28,0.480602,0.552850,Restaurants,0.7,15.0,1.0,10,0.0,1.0,1,11,4.4,"{""primary_tags"":""32""}",Burgers

In [7]:
from sklearn.preprocessing import MultiLabelBinarizer

In [11]:
mlb = MultiLabelBinarizer()

In [9]:
vendor['vendor_tag_name'] = vendor['vendor_tag_name'].fillna('[]')

def to_list(string):
    ls = list(string.split(','))
    return ls
vendor['vendor_tag_name'] = vendor['vendor_tag_name'].apply(to_list)

In [10]:
vendor.head()

,id,latitude,longitude,vendor_category_en,delivery_charge,serving_distance,is_open,prepration_time,discount_percentage,status,verified,rank,vendor_rating,primary_tags,vendor_tag_name
0,4,-0.588596,0.754434,Restaurants,0.0,6.0,1.0,15,0.0,1.0,1,11,4.4,"{""primary_tags"":""4""}","[Arabic, Breakfast, Burgers, Desserts, Free De..."
1,13,-0.471654,0.744470,Restaurants,0.7,5.0,1.0,14,0.0,1.0,1,11,4.7,"{""primary_tags"":""7""}","[Breakfast, Cakes, Crepes, Italian, Pasta, Piz..."
2,20,-0.407527,0.643681,Restaurants,0.0,8.0,1.0,19,0.0,1.0,1,1,4.5,"{""primary_tags"":""71""}","[Breakfast, Desserts, Free Delivery, Indian]"
3,23,-0.585385,0.753811,Restaurants,0.0,5.0,1.0,16,0.0,1.0,1,11,4.5,"{""primary_tags"":""46""}","[Burgers, Desserts, Fries, Salads]"
4,28,0.480602,0.552850,Restaurants,0.7,15.0,1.0,10,0.0,1.0,1,11,4.4,"{""primary_tags"":""32""}",[Burgers]

In [21]:
X = vendor['vendor_tag_name']

In [22]:
X = mlb.fit_transform(X)

In [23]:
mlb.classes_

array(['American', 'Arabic', 'Asian', 'Bagels', 'Biryani', 'Breakfast',
       'Burgers', 'Cafe', 'Cakes', 'Chinese', 'Churros', 'Coffee',
       'Combos', 'Crepes', 'Desserts', 'Dimsum', 'Donuts', 'Family Meal',
       'Fatayers', 'Free Delivery', 'Fresh Juices', 'Fries',
       'Frozen yoghurt', 'Grills', 'Healthy Food', 'Hot Chocolate',
       'Hot Dogs', 'Ice creams', 'Indian', 'Italian', 'Japanese', 'Karak',
       'Kebabs', 'Kids meal', 'Kushari', 'Lebanese', 'Manakeesh',
       'Mandazi', 'Mexican', 'Milkshakes', 'Mishkak', 'Mojitos',
       'Mojitos ', 'Omani', 'Organic', 'Pancakes', 'Pasta', 'Pastas',
       'Pastry', 'Pizza', 'Pizzas', 'Rice', 'Rolls', 'Salads',
       'Sandwiches', 'Seafood', 'Shawarma', 'Shuwa', 'Smoothies', 'Soups',
       'Spanish Latte', 'Steaks', 'Sushi', 'Sweets', 'Thai', 'Thali',
       'Vegetarian', 'Waffles', '[]'], dtype=object)

In [26]:
vendor = pd.merge(vendor, X)

TypeError: Can only merge Series or DataFrame objects, a <class 'numpy.ndarray'> was passed

In [25]:
vendor.head()

,id,latitude,longitude,vendor_category_en,delivery_charge,serving_distance,is_open,prepration_time,discount_percentage,status,verified,rank,vendor_rating,primary_tags,vendor_tag_name
0,4,-0.588596,0.754434,Restaurants,0.0,6.0,1.0,15,0.0,1.0,1,11,4.4,"{""primary_tags"":""4""}",0
1,13,-0.471654,0.744470,Restaurants,0.7,5.0,1.0,14,0.0,1.0,1,11,4.7,"{""primary_tags"":""7""}",0
2,20,-0.407527,0.643681,Restaurants,0.0,8.0,1.0,19,0.0,1.0,1,1,4.5,"{""primary_tags"":""71""}",0
3,23,-0.585385,0.753811,Restaurants,0.0,5.0,1.0,16,0.0,1.0,1,11,4.5,"{""primary_tags"":""46""}",0
4,28,0.480602,0.552850,Restaurants,0.7,15.0,1.0,10,0.0,1.0,1,11,4.4,"{""primary_tags"":""32""}",0

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
oe = OneHotEncoder(handle_unknown='ignore')
X = vendor['vendor_tag_name']

In [20]:
oe.fit(X)

ValueError: Expected 2D array, got 1D array instead:
array=[list(['Arabic', 'Breakfast', 'Burgers', 'Desserts', 'Free Delivery', 'Grills', 'Lebanese', 'Salads', 'Sandwiches', 'Shawarma'])
 list(['Breakfast', 'Cakes', 'Crepes', 'Italian', 'Pasta', 'Pizzas', 'Salads', 'Sandwiches', 'Soups'])
 list(['Breakfast', 'Desserts', 'Free Delivery', 'Indian'])
 list(['Burgers', 'Desserts', 'Fries', 'Salads']) list(['Burgers'])
 list(['Desserts', 'Mexican'])
 list(['American', 'Burgers', 'Fries', 'Sandwiches'])
 list(['American', 'Burgers', 'Fries', 'Sandwiches'])
 list(['Breakfast', 'Desserts', 'Grills', 'Milkshakes', 'Salads', 'Sandwiches', 'Soups'])
 list(['Breakfast', 'Burgers', 'Desserts', 'Indian', 'Salads'])
 list(['Breakfast', 'Desserts', 'Grills', 'Milkshakes', 'Salads', 'Sandwiches', 'Soups'])
 list(['Asian', 'Desserts', 'Healthy Food', 'Japanese', 'Salads', 'Sushi'])
 list(['Sandwiches', 'Breakfast', 'Burgers', 'Mojitos'])
 list(['Pizzas', 'Italian', 'Breakfast', 'Soups', 'Pasta', 'Salads', 'Desserts'])
 list(['Burgers', 'Desserts', 'Free Delivery', 'Pasta', 'Sandwiches'])
 list(['Arabic', 'Breakfast', 'Desserts', 'Mandazi', 'Omani', 'Salads', 'Sandwiches'])
 list(['Breakfast', 'Desserts', 'Lebanese', 'Manakeesh', 'Pizzas', 'Salads', 'Sandwiches'])
 list(['Breakfast', 'Desserts', 'Salads', 'Arabic'])
 list(['Burgers', 'Fries', 'Kids meal', 'Shawarma'])
 list(['Desserts', 'Omani'])
 list(['Cakes', 'Crepes', 'Desserts', 'Donuts', 'Fresh Juices', 'Ice creams', 'Milkshakes', 'Pancakes', 'Waffles'])
 list(['American', 'Burgers', 'Desserts', 'Mojitos ', 'Pasta'])
 list(['Asian', 'Fresh Juices', 'Kids meal'])
 list(['American', 'Burgers', 'Free Delivery', 'Hot Dogs', 'Pasta'])
 list(['American', 'Burgers', 'Free Delivery', 'Hot Dogs', 'Pasta'])
 list(['American', 'Burgers', 'Free Delivery', 'Hot Dogs', 'Pasta'])
 list(['Asian', 'Dimsum', 'Grills', 'Japanese', 'Rice', 'Soups'])
 list(['Arabic', 'Desserts', 'Free Delivery', 'Indian'])
 list(['Desserts', 'Free Delivery', 'Healthy Food', 'Sweets'])
 list(['Burgers', 'Healthy Food', 'Milkshakes', 'Sandwiches', 'Steaks'])
 list(['Arabic', 'Pizzas', 'Sandwiches'])
 list(['Breakfast', 'Burgers', 'Grills', 'Pizza', 'Sandwiches', 'Shawarma'])
 list(['Arabic'])
 list(['American', 'Burgers', 'Mishkak', 'Salads', 'Sandwiches'])
 list(['Biryani', 'Desserts', 'Indian', 'Rice', 'Thali', 'Vegetarian'])
 list(['American', 'Burgers', 'Sandwiches'])
 list(['American', 'Burgers', 'Kids meal', 'Sandwiches'])
 list(['Burgers', 'Desserts', 'Pastry', 'Pizzas'])
 list(['Breakfast', 'Desserts', 'Grills', 'Milkshakes', 'Salads', 'Sandwiches', 'Soups'])
 list(['Arabic', 'Grills', 'Indian', 'Pasta', 'Salads', 'Seafood', 'Soups', 'Sweets'])
 list(['Italian', 'Pasta', 'Pizzas', 'Salads', 'Sandwiches'])
 list(['Sandwiches', 'Shawarma', 'Fresh Juices', 'Mojitos', 'Milkshakes'])
 list(['Fresh Juices', 'Milkshakes', 'Mojitos ', 'Sandwiches', 'Shawarma'])
 list(['Fresh Juices', 'Milkshakes', 'Mojitos ', 'Sandwiches', 'Shawarma'])
 list(['Arabic', 'Burgers', 'Sandwiches', 'Shawarma', 'Grills', 'Pizzas', 'Desserts'])
 list(['Burgers', 'Fries', 'Grills', 'Mishkak', 'Mojitos ', 'Sandwiches', 'Sweets'])
 list(['[]']) list(['Free Delivery', 'Mexican', 'Salads'])
 list(['Cakes', 'Crepes', 'Desserts', 'Donuts', 'Fresh Juices', 'Ice creams', 'Milkshakes', 'Mojitos ', 'Pancakes', 'Waffles'])
 list(['Biryani', 'Desserts', 'Indian', 'Soups'])
 list(['American', 'Sandwiches', 'Hot Dogs', 'Fries'])
 list(['Arabic', 'Biryani', 'Chinese', 'Grills', 'Indian', 'Rice', 'Salads', 'Soups', 'Thai'])
 list(['Coffee', 'Organic'])
 list(['Fresh Juices', 'Healthy Food', 'Smoothies'])
 list(['Breakfast', 'Free Delivery', 'Fresh Juices', 'Fries', 'Karak', 'Mojitos ', 'Rolls'])
 list(['[]'])
 list(['American', 'Burgers', 'Desserts', 'Donuts', 'Fries', 'Pasta', 'Salads', 'Sandwiches'])
 list(['[]'])
 list(['American', 'Breakfast', 'Rolls', 'Salads', 'Sandwiches'])
 list(['American', 'Burgers', 'Kids meal', 'Pasta', 'Sandwiches', 'Smoothies', 'Soups', 'Steaks'])
 list(['Desserts', 'Free Delivery', 'Fresh Juices', 'Healthy Food', 'Ice creams', 'Milkshakes', 'Mojitos '])
 list(['American', 'Burgers', 'Kids meal', 'Pasta', 'Sandwiches', 'Smoothies', 'Soups', 'Steaks'])
 list(['Cakes', 'Donuts'])
 list(['Asian', 'Desserts', 'Rice', 'Salads', 'Soups', 'Thai'])
 list(['American', 'Burgers', 'Fries', 'Mojitos '])
 list(['Burgers', 'Desserts', 'Free Delivery', 'Grills', 'Mexican'])
 list(['Coffee', 'Fresh Juices', 'Hot Chocolate', 'Sandwiches', 'Smoothies'])
 list(['Free Delivery', 'Fresh Juices', 'Pastas', 'Salads', 'Sandwiches'])
 list(['Combos', 'Fries', 'Mojitos ', 'Pasta', 'Sandwiches'])
 list(['Coffee', 'Fresh Juices', 'Hot Chocolate', 'Sandwiches', 'Smoothies'])
 list(['Coffee', 'Fresh Juices', 'Hot Chocolate', 'Sandwiches', 'Smoothies'])
 list(['American', 'Breakfast', 'Burgers', 'Fries', 'Sandwiches'])
 list(['Bagels', 'Desserts', 'Salads'])
 list(['American', 'Kids meal', 'Pasta', 'Pizzas', 'Salads'])
 list(['Churros'])
 list(['American', 'Breakfast', 'Burgers', 'Desserts', 'Italian', 'Salads', 'Sandwiches', 'Soups', 'Steaks'])
 list(['Omani', 'Arabic', 'Shuwa', 'Pasta', 'Rice', 'Soups', 'Lebanese'])
 list(['Frozen yoghurt', 'Smoothies'])
 list(['Arabic', 'Kushari', 'Sandwiches'])
 list(['Burgers', 'Free Delivery', 'Milkshakes', 'Mojitos '])
 list(['American', 'Burgers', 'Desserts', 'Free Delivery', 'Fries', 'Hot Dogs', 'Kids meal'])
 list(['Fresh Juices', 'Lebanese', 'Sandwiches', 'Shawarma'])
 list(['Burgers', 'Desserts', 'Free Delivery', 'Pasta', 'Sandwiches'])
 list(['Coffee', 'Pancakes', 'Spanish Latte', 'Waffles'])
 list(['Burgers', 'Desserts', 'Family Meal', 'Salads'])
 list(['Fresh Juices', 'Sandwiches', 'Shawarma'])
 list(['Fresh Juices', 'Sandwiches', 'Shawarma'])
 list(['Fresh Juices', 'Sandwiches', 'Shawarma'])
 list(['Biryani', 'Desserts', 'Indian', 'Kebabs', 'Rice'])
 list(['Biryani', 'Desserts', 'Indian', 'Kebabs', 'Rice'])
 list(['Biryani', 'Desserts', 'Indian', 'Kebabs', 'Rice'])
 list(['American', 'Breakfast', 'Burgers', 'Cafe', 'Desserts', 'Free Delivery', 'Fries', 'Ice creams', 'Kids meal', 'Salads'])
 list(['American', 'Breakfast', 'Burgers', 'Cafe', 'Desserts', 'Free Delivery', 'Fries', 'Ice creams', 'Kids meal', 'Salads'])
 list(['American', 'Breakfast', 'Burgers', 'Cafe', 'Desserts', 'Free Delivery', 'Fries', 'Ice creams', 'Kids meal', 'Salads'])
 list(['American', 'Breakfast', 'Burgers', 'Cafe', 'Desserts', 'Free Delivery', 'Fries', 'Ice creams', 'Kids meal', 'Salads'])
 list(['American', 'Breakfast', 'Burgers', 'Cafe', 'Desserts', 'Free Delivery', 'Fries', 'Ice creams', 'Kids meal', 'Salads'])
 list(['American', 'Burgers', 'Desserts', 'Free Delivery', 'Fries', 'Kids meal', 'Salads'])
 list(['American', 'Breakfast', 'Burgers', 'Cafe', 'Desserts', 'Free Delivery', 'Fries', 'Ice creams', 'Kids meal', 'Salads'])
 list(['American', 'Breakfast', 'Burgers', 'Cafe', 'Desserts', 'Free Delivery', 'Fries', 'Ice creams', 'Kids meal', 'Salads'])
 list(['Fatayers', 'Mojitos ', 'Sandwiches'])].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [5]:
vendor.head()

,OpeningTime,OpeningTime2,sunday_from_time1,sunday_to_time1,primary_tags,vendor_tag,vendor_tag_name
0,11:00AM-11:30PM,-,00:00:00,00:30:00,"{""primary_tags"":""4""}","2,4,5,8,91,22,12,24,16,23","Arabic,Breakfast,Burgers,Desserts,Free Deliver..."
1,08:30AM-10:30PM,-,00:00:00,01:30:00,"{""primary_tags"":""7""}","4,41,51,34,27,15,24,16,28","Breakfast,Cakes,Crepes,Italian,Pasta,Pizzas,Sa..."
2,08:00AM-10:45PM,-,08:00:00,22:45:00,"{""primary_tags"":""71""}","4,8,91,10","Breakfast,Desserts,Free Delivery,Indian"
3,10:59AM-10:30PM,-,09:00:00,23:30:00,"{""primary_tags"":""46""}","5,8,30,24","Burgers,Desserts,Fries,Salads"
4,11:00AM-11:45PM,-,00:01:00,00:30:00,"{""primary_tags"":""32""}",5,Burgers

In [6]:
vendor['opening_time'] = vendor['OpeningTime'].str[:7]
vendor['closing_time'] = vendor['OpeningTime'].str[8:]

In [7]:
vendor.head()

,OpeningTime,OpeningTime2,sunday_from_time1,sunday_to_time1,primary_tags,vendor_tag,vendor_tag_name,opening_time,closing_time
0,11:00AM-11:30PM,-,00:00:00,00:30:00,"{""primary_tags"":""4""}","2,4,5,8,91,22,12,24,16,23","Arabic,Breakfast,Burgers,Desserts,Free Deliver...",11:00AM,11:30PM
1,08:30AM-10:30PM,-,00:00:00,01:30:00,"{""primary_tags"":""7""}","4,41,51,34,27,15,24,16,28","Breakfast,Cakes,Crepes,Italian,Pasta,Pizzas,Sa...",08:30AM,10:30PM
2,08:00AM-10:45PM,-,08:00:00,22:45:00,"{""primary_tags"":""71""}","4,8,91,10","Breakfast,Desserts,Free Delivery,Indian",08:00AM,10:45PM
3,10:59AM-10:30PM,-,09:00:00,23:30:00,"{""primary_tags"":""46""}","5,8,30,24","Burgers,Desserts,Fries,Salads",10:59AM,10:30PM
4,11:00AM-11:45PM,-,00:01:00,00:30:00,"{""primary_tags"":""32""}",5,Burgers,11:00AM,11:45PM